import type { ChatbotConfig, QuickReply } from "./types"

const mainQuickReplies: QuickReply[] = [
  {
    id: "qr-medecin-traitant",
    label: "Trouver un médecin traitant",
    value: "medecin traitant",
    nextNodeId: "medecin-traitant",
  },
  {
    id: "qr-urgences",
    label: "Urgences et numéros utiles",
    value: "urgences",
    nextNodeId: "urgences",
  },
  {
    id: "qr-sante-mentale",
    label: "Santé mentale",
    value: "sante mentale",
    nextNodeId: "sante-mentale",
  },
  {
    id: "qr-annuaire",
    label: "Trouver un professionnel",
    value: "annuaire",
    nextNodeId: "annuaire",
  },
  {
    id: "qr-presentation-cpts",
    label: "Comprendre la CPTS",
    value: "presentation cpts",
    nextNodeId: "presentation-node",
  },
  {
    id: "qr-mon-espace-sante",
    label: "Mon Espace Santé",
    value: "mon espace sante",
    nextNodeId: "mon-espace-sante-node",
  },
  {
    id: "qr-pro",
    label: "Ressources professionnels",
    value: "ressources professionnels",
    nextNodeId: "professionnels",
  },
  {
    id: "qr-supports",
    label: "Commander des supports",
    value: "commander des supports",
    nextNodeId: "supports",
  },
  {
    id: "qr-formations",
    label: "Formations CPTS",
    value: "formations cpts",
    nextNodeId: "formations",
  },
  {
    id: "qr-prevention",
    label: "Prévention santé familiale",
    value: "prevention",
    nextNodeId: "prevention",
  },
  {
    id: "qr-faq",
    label: "FAQ / questions fréquentes",
    value: "faq",
    nextNodeId: "faq",
  },
]

const restartQuickReply: QuickReply = {
  id: "qr-retour-accueil",
  label: "Revenir au menu principal",
  value: "menu principal",
  nextNodeId: "start",
}

export const chatbotConfig: ChatbotConfig = {
  resources: {
    "medecin-traitant": {
      id: "medecin-traitant",
      type: "internal",
      title: "Avez-vous un médecin traitant ?",
      description: "Parcours et informations pour trouver un médecin traitant.",
      href: "/patients/medecin-traitant",
    },
    annuaire: {
      id: "annuaire",
      type: "internal",
      title: "Annuaire des professionnels de santé",
      description: "Rechercher un professionnel selon votre besoin.",
      href: "/patients/annuaire",
    },
    presentation: {
      id: "presentation",
      type: "internal",
      title: "Présentation de la CPTS",
      description: "Comprendre ce qu'est la CPTS, son organisation et ses missions.",
      href: "/presentation",
    },
    coordonnees: {
      id: "coordonnees",
      type: "internal",
      title: "Coordonnées utiles",
      description: "Tous les contacts essentiels pour urgences et soins non programmés.",
      href: "/patients/coordonnees",
    },
    "mon-espace-sante": {
      id: "mon-espace-sante",
      type: "internal",
      title: "Mon Espace Santé",
      description: "Page explicative pour comprendre et utiliser l'application Mon Espace Santé.",
      href: "/patients/mon-espace-sante",
    },
    "sante-mentale": {
      id: "sante-mentale",
      type: "internal",
      title: "Ressources santé mentale",
      description: "Aides, articles et outils sur la santé mentale.",
      href: "/sante-mental",
    },
    "sante-mentale-jeunes": {
      id: "sante-mentale-jeunes",
      type: "internal",
      title: "Santé mentale des jeunes",
      description: "Ressources spécifiques pour les jeunes et leurs proches.",
      href: "/prevention/sante-familiale/sante-mentale-des-jeunes",
    },
    "prevention-familiale": {
      id: "prevention-familiale",
      type: "internal",
      title: "Articles santé familiale",
      description: "Vaccination, dépistage, sommeil, prévention du quotidien.",
      href: "/prevention/sante-familiale",
    },
    "memos-suivi": {
      id: "memos-suivi",
      type: "internal",
      title: "Fiches de suivi",
      description: "Ressources de suivi et prévention disponibles pour les patients.",
      href: "/prevention/memos-suivi",
    },
    "ms-diabete": {
      id: "ms-diabete",
      type: "internal",
      title: "Mémo suivi - Diabète",
      description: "Ouvrir le mémo de suivi dédié au diabète.",
      href: "/prevention/memos-suivi?openMemo=diabete",
    },
    "ms-hypertension": {
      id: "ms-hypertension",
      type: "internal",
      title: "Mémo suivi - Hypertension artérielle",
      description: "Ouvrir le mémo de suivi dédié à l'hypertension artérielle.",
      href: "/prevention/memos-suivi?openMemo=hypertension",
    },
    "ms-insuffisance-cardiaque": {
      id: "ms-insuffisance-cardiaque",
      type: "internal",
      title: "Mémo suivi - Insuffisance cardiaque",
      description: "Article de suivi dédié à l'insuffisance cardiaque.",
      href: "/prevention/memos-suivi?openMemo=insuffisance-cardiaque",
    },
    "ms-grossesse": {
      id: "ms-grossesse",
      type: "internal",
      title: "Mémo suivi - Grossesse",
      description: "Ouvrir le mémo de suivi dédié à la grossesse.",
      href: "/prevention/memos-suivi?openMemo=grossesse",
    },
    "ms-prevention-sexuelle": {
      id: "ms-prevention-sexuelle",
      type: "internal",
      title: "Mémo suivi - Prévention santé sexuelle",
      description: "Ouvrir le mémo prévention santé sexuelle.",
      href: "/prevention/memos-suivi?openMemo=prevention-sexuelle",
    },
    "ms-bon-usage-systeme-sante": {
      id: "ms-bon-usage-systeme-sante",
      type: "internal",
      title: "Mémo suivi - Bon usage du système de santé",
      description: "Ouvrir le mémo bon usage du système de santé.",
      href: "/prevention/memos-suivi?openMemo=bon-usage",
    },
    "ms-parent-planner": {
      id: "ms-parent-planner",
      type: "internal",
      title: "Mémo suivi - Parent Planner",
      description: "Ouvrir le mémo Parent Planner.",
      href: "/prevention/memos-suivi?openMemo=parent-planner",
    },
    "sf-insomnie": {
      id: "sf-insomnie",
      type: "internal",
      title: "Santé familiale - Insomnie",
      description: "Comprendre l'insomnie et les solutions de prise en charge.",
      href: "/prevention/sante-familiale/insomnie",
    },
    "sf-mois-sans-tabac-2025": {
      id: "sf-mois-sans-tabac-2025",
      type: "internal",
      title: "Santé familiale - Mois sans tabac 2025",
      description: "Article de prévention et d'accompagnement à l'arrêt du tabac.",
      href: "/prevention/sante-familiale/mois-sans-tabac-novembre-2025",
    },
    "sf-movember-2026": {
      id: "sf-movember-2026",
      type: "internal",
      title: "Santé familiale - Movember 2026",
      description: "Campagne de prévention santé masculine.",
      href: "/prevention/sante-familiale/movember-2026",
    },
    "sf-octobre-rose-2025": {
      id: "sf-octobre-rose-2025",
      type: "internal",
      title: "Santé familiale - Octobre rose 2025",
      description: "Campagne de sensibilisation et dépistage du cancer du sein.",
      href: "/prevention/sante-familiale/octobre-rose-2025",
    },
    "sf-mars-bleu-2026": {
      id: "sf-mars-bleu-2026",
      type: "internal",
      title: "Santé familiale - Mars bleu 2026",
      description: "Prévention du cancer colorectal et dépistage organisé.",
      href: "/prevention/sante-familiale/prevention-cancer-colorectal-mars-bleu-2026",
    },
    "sf-vaccination-covid-2025": {
      id: "sf-vaccination-covid-2025",
      type: "internal",
      title: "Santé familiale - Vaccination anti-COVID 2025",
      description: "Informations de prévention sur la vaccination anti-COVID.",
      href: "/prevention/sante-familiale/vaccination-anti-covid-2025",
    },
    "sf-vaccination-grippe-2025": {
      id: "sf-vaccination-grippe-2025",
      type: "internal",
      title: "Santé familiale - Vaccination antigrippale 2025",
      description: "Informations de prévention sur la vaccination contre la grippe.",
      href: "/prevention/sante-familiale/vaccination-anti-grippale-2025",
    },
    "etp-apnee-sommeil": {
      id: "etp-apnee-sommeil",
      type: "internal",
      title: "Éducation thérapeutique - Syndrome d'apnée du sommeil",
      description: "Ressource dédiée au syndrome d'apnée du sommeil.",
      href: "/prevention/education-therapeutique/syndrome-apnee-sommeil",
    },
    "sante-mentale-annuaire": {
      id: "sante-mentale-annuaire",
      type: "internal",
      title: "Annuaire santé mentale",
      description: "Accès à l'annuaire santé mentale (ouverture directe de l'annuaire).",
      href: "/sante-mental?open=annuaire",
    },
    "pro-adhesion": {
      id: "pro-adhesion",
      type: "internal",
      title: "Adhérer à la CPTS",
      description: "Page d'adhésion des professionnels à la CPTS.",
      href: "/professionnels/adhesion",
    },
    "pro-actions-outils": {
      id: "pro-actions-outils",
      type: "internal",
      title: "Nos actions & vos outils (professionnels)",
      description: "Toutes les ressources et outils destinés aux professionnels de santé.",
      href: "/professionnels/actions-outils",
    },
    "pro-supports": {
      id: "pro-supports",
      type: "internal",
      title: "Commander des supports",
      description:
        "Page de commande des supports pour adhérents. La demande est envoyée par email à la coordinatrice CPTS, puis impression et livraison.",
      href: "/professionnels/supports",
    },
    "pro-formations": {
      id: "pro-formations",
      type: "internal",
      title: "Formations CPTS",
      description: "Formations à venir et passées, avec possibilité d'inscription.",
      href: "/professionnels/formations",
    },
    "ao-questionnaire-medecin": {
      id: "ao-questionnaire-medecin",
      type: "external",
      title: "Questionnaire MÉDECIN - Patient sans médecin traitant",
      href: "/actions-outils/medecin-traitan/Questionnaire-MEDECIN-Patient-sans-MT-A-TELECHARGER.pdf",
    },
    "ao-questionnaire-paramedical": {
      id: "ao-questionnaire-paramedical",
      type: "external",
      title: "Questionnaire PARAMÉDICAL - Patient sans médecin traitant",
      href: "/actions-outils/medecin-traitan/Patient-sans-MT-Questionnaire-PARAMED-nov-23.pdf",
    },
    "ao-formulaire-mas": {
      id: "ao-formulaire-mas",
      type: "external",
      title: "Formulaire MAS",
      href: "/actions-outils/Formulaire-MAS-a-telecharger.pdf",
    },
    "ao-affiche-pharmacies": {
      id: "ao-affiche-pharmacies",
      type: "external",
      title: "Pharmacies participantes (SNP)",
      href: "/actions-outils/Affiche-Pharmacies-CPTS-OG.pdf",
    },
    "ao-questions-psy": {
      id: "ao-questions-psy",
      type: "external",
      title: "Questions Psy",
      href: "/actions-outils/sante-mentale/Questions-Psy.pdf",
    },
    "ao-emsi2": {
      id: "ao-emsi2",
      type: "external",
      title: "emsi²",
      href: "/actions-outils/sante-mentale/emsi%C2%B2.pdf",
    },
    "ao-reponse-psy": {
      id: "ao-reponse-psy",
      type: "external",
      title: "Réponse Psy",
      href: "/actions-outils/sante-mentale/flyer-Reponse-Psy.pdf",
    },
    "ao-livret-mss": {
      id: "ao-livret-mss",
      type: "external",
      title: "Livret MSS",
      href: "/actions-outils/livret-MSS-.pdf",
    },
    "ao-poletp": {
      id: "ao-poletp",
      type: "external",
      title: "Pôle ETP",
      href: "https://www.poletpna.fr/",
    },
    "ao-maison-nutrition": {
      id: "ao-maison-nutrition",
      type: "external",
      title: "Maison Nutrition Diabète Coeur",
      href: "https://www.maisonnutrition33.com/",
    },
    "ao-medprev": {
      id: "ao-medprev",
      type: "external",
      title: "Campagne Medprev",
      href: "https://medprev.org/",
    },
    "ao-mots": {
      id: "ao-mots",
      type: "external",
      title: "Association MOTS",
      href: "https://www.association-mots.org/",
    },
    faq: {
      id: "faq",
      type: "internal",
      title: "FAQ",
      description: "Réponses aux questions les plus fréquentes.",
      href: "/faq",
    },
    "contact-email": {
      id: "contact-email",
      type: "email",
      title: "Contacter la CPTS par email",
      description: "Pour une demande générale ou une orientation complémentaire.",
      value: "info@cpts-ouest-gironde.fr",
    },
    "urgence-3114": {
      id: "urgence-3114",
      type: "phone",
      title: "Prévention suicide - 3114",
      description: "Numéro national 24h/24, 7j/7.",
      value: "3114",
    },
  },
  keywordIndex: [
    { keyword: "medecin traitant", resourceId: "medecin-traitant", scoreBoost: 12 },
    { keyword: "recherche medecin", resourceId: "medecin-traitant" },
    { keyword: "cpts", resourceId: "presentation", scoreBoost: 6 },
    { keyword: "presentation cpts", resourceId: "presentation", scoreBoost: 12 },
    { keyword: "communaute professionnelle territoriale de sante", resourceId: "presentation", scoreBoost: 12 },
    { keyword: "patient sans medecin", resourceId: "ao-questionnaire-medecin" },
    { keyword: "questionnaire medecin", resourceId: "ao-questionnaire-medecin" },
    { keyword: "questionnaire paramedical", resourceId: "ao-questionnaire-paramedical" },

    { keyword: "annuaire", resourceId: "annuaire", scoreBoost: 8 },
    { keyword: "specialiste", resourceId: "annuaire" },
    { keyword: "professionnel", resourceId: "annuaire" },

    { keyword: "urgence", resourceId: "coordonnees", scoreBoost: 10 },
    { keyword: "samu", resourceId: "coordonnees" },
    { keyword: "112", resourceId: "coordonnees" },

    { keyword: "sante mentale", resourceId: "sante-mentale", scoreBoost: 9 },
    { keyword: "annuaire sante mentale", resourceId: "sante-mentale-annuaire", scoreBoost: 16 },
    { keyword: "annuaire psy", resourceId: "sante-mentale-annuaire", scoreBoost: 12 },
    { keyword: "trouver un psy", resourceId: "sante-mentale-annuaire", scoreBoost: 10 },
    { keyword: "depression", resourceId: "sante-mentale" },
    { keyword: "angoisse", resourceId: "sante-mentale" },
    { keyword: "suicide", resourceId: "urgence-3114", scoreBoost: 10 },
    { keyword: "sante mentale jeunes", resourceId: "sante-mentale-jeunes", scoreBoost: 12 },
    { keyword: "adolescent", resourceId: "sante-mentale-jeunes" },
    { keyword: "questions psy", resourceId: "ao-questions-psy", scoreBoost: 10 },
    { keyword: "reponse psy", resourceId: "ao-reponse-psy", scoreBoost: 10 },
    { keyword: "emsi", resourceId: "ao-emsi2", scoreBoost: 8 },

    { keyword: "mon espace sante", resourceId: "mon-espace-sante", scoreBoost: 12 },
    { keyword: "application sante", resourceId: "mon-espace-sante" },

    { keyword: "prevention", resourceId: "prevention-familiale" },
    { keyword: "vaccination", resourceId: "prevention-familiale" },
    { keyword: "memos suivi", resourceId: "memos-suivi", scoreBoost: 8 },
    { keyword: "fiches de suivi", resourceId: "memos-suivi", scoreBoost: 8 },
    { keyword: "diabete", resourceId: "ms-diabete", scoreBoost: 14 },
    { keyword: "memo diabete", resourceId: "ms-diabete", scoreBoost: 14 },
    { keyword: "hypertension arterielle", resourceId: "ms-hypertension", scoreBoost: 14 },
    { keyword: "hta", resourceId: "ms-hypertension", scoreBoost: 10 },
    { keyword: "insuffisance cardiaque", resourceId: "ms-insuffisance-cardiaque", scoreBoost: 14 },
    { keyword: "memo insuffisance cardiaque", resourceId: "ms-insuffisance-cardiaque", scoreBoost: 14 },
    { keyword: "grossesse", resourceId: "ms-grossesse", scoreBoost: 12 },
    { keyword: "suivi grossesse", resourceId: "ms-grossesse", scoreBoost: 12 },
    { keyword: "prevention sexuelle", resourceId: "ms-prevention-sexuelle", scoreBoost: 16 },
    { keyword: "sante sexuelle", resourceId: "ms-prevention-sexuelle", scoreBoost: 14 },
    { keyword: "ist", resourceId: "ms-prevention-sexuelle", scoreBoost: 12 },
    { keyword: "hpv", resourceId: "ms-prevention-sexuelle", scoreBoost: 12 },
    { keyword: "contraception", resourceId: "ms-prevention-sexuelle", scoreBoost: 12 },
    { keyword: "systeme de sante", resourceId: "ms-bon-usage-systeme-sante", scoreBoost: 16 },
    { keyword: "bon usage du systeme de sante", resourceId: "ms-bon-usage-systeme-sante", scoreBoost: 16 },
    { keyword: "bon usage systeme", resourceId: "ms-bon-usage-systeme-sante", scoreBoost: 14 },
    { keyword: "parent planner", resourceId: "ms-parent-planner", scoreBoost: 12 },
    { keyword: "doudou liste", resourceId: "ms-parent-planner", scoreBoost: 12 },
    { keyword: "insomnie", resourceId: "sf-insomnie", scoreBoost: 12 },
    { keyword: "trouble du sommeil", resourceId: "sf-insomnie", scoreBoost: 10 },
    { keyword: "sommeil", resourceId: "sf-insomnie", scoreBoost: 8 },
    { keyword: "apnee du sommeil", resourceId: "etp-apnee-sommeil", scoreBoost: 16 },
    { keyword: "syndrome apnee sommeil", resourceId: "etp-apnee-sommeil", scoreBoost: 14 },
    { keyword: "apnee sommeil", resourceId: "etp-apnee-sommeil", scoreBoost: 14 },
    { keyword: "mois sans tabac", resourceId: "sf-mois-sans-tabac-2025", scoreBoost: 14 },
    { keyword: "tabac", resourceId: "sf-mois-sans-tabac-2025", scoreBoost: 10 },
    { keyword: "arret tabac", resourceId: "sf-mois-sans-tabac-2025", scoreBoost: 10 },
    { keyword: "movember", resourceId: "sf-movember-2026", scoreBoost: 16 },
    { keyword: "sante masculine", resourceId: "sf-movember-2026", scoreBoost: 12 },
    { keyword: "octobre rose", resourceId: "sf-octobre-rose-2025", scoreBoost: 16 },
    { keyword: "cancer du sein", resourceId: "sf-octobre-rose-2025", scoreBoost: 12 },
    { keyword: "mars bleu", resourceId: "sf-mars-bleu-2026", scoreBoost: 16 },
    { keyword: "cancer colorectal", resourceId: "sf-mars-bleu-2026", scoreBoost: 14 },
    { keyword: "colo rectal", resourceId: "sf-mars-bleu-2026", scoreBoost: 12 },
    { keyword: "depistage colorectal", resourceId: "sf-mars-bleu-2026", scoreBoost: 12 },
    { keyword: "vaccination anti covid", resourceId: "sf-vaccination-covid-2025", scoreBoost: 14 },
    { keyword: "anti covid", resourceId: "sf-vaccination-covid-2025", scoreBoost: 10 },
    { keyword: "covid", resourceId: "sf-vaccination-covid-2025", scoreBoost: 8 },
    { keyword: "vaccination anti grippale", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 14 },
    { keyword: "vaccination grippe", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 12 },
    { keyword: "grippe", resourceId: "sf-vaccination-grippe-2025", scoreBoost: 8 },

    { keyword: "actions outils", resourceId: "pro-actions-outils", scoreBoost: 12 },
    { keyword: "ressources professionnels", resourceId: "pro-actions-outils", scoreBoost: 12 },
    { keyword: "outils pro", resourceId: "pro-actions-outils", scoreBoost: 10 },

    { keyword: "supports", resourceId: "pro-supports", scoreBoost: 11 },
    { keyword: "commande support", resourceId: "pro-supports", scoreBoost: 12 },
    { keyword: "coordinatrice", resourceId: "pro-supports" },
    { keyword: "imprimer", resourceId: "pro-supports" },
    { keyword: "livrer", resourceId: "pro-supports" },

    { keyword: "formation", resourceId: "pro-formations", scoreBoost: 12 },
    { keyword: "formations", resourceId: "pro-formations", scoreBoost: 12 },
    { keyword: "inscription", resourceId: "pro-formations", scoreBoost: 8 },
    { keyword: "formation a venir", resourceId: "pro-formations", scoreBoost: 10 },
    { keyword: "adherer", resourceId: "pro-adhesion", scoreBoost: 12 },
    { keyword: "adhesion", resourceId: "pro-adhesion", scoreBoost: 12 },
    { keyword: "devenir adherent", resourceId: "pro-adhesion", scoreBoost: 12 },
    { keyword: "adhesion professionnel", resourceId: "pro-adhesion", scoreBoost: 12 },
    { keyword: "aderer", resourceId: "pro-adhesion", scoreBoost: 12 },

    { keyword: "formulaire mas", resourceId: "ao-formulaire-mas", scoreBoost: 10 },
    { keyword: "pharmacies participantes", resourceId: "ao-affiche-pharmacies", scoreBoost: 10 },
    { keyword: "livret mss", resourceId: "ao-livret-mss", scoreBoost: 10 },
    { keyword: "pole etp", resourceId: "ao-poletp", scoreBoost: 10 },
    { keyword: "maison nutrition", resourceId: "ao-maison-nutrition", scoreBoost: 10 },
    { keyword: "medprev", resourceId: "ao-medprev", scoreBoost: 10 },
    { keyword: "mots", resourceId: "ao-mots", scoreBoost: 8 },
    { keyword: "burn out", resourceId: "ao-mots", scoreBoost: 10 },
    { keyword: "epuisement soignant", resourceId: "ao-mots", scoreBoost: 10 },

    { keyword: "faq", resourceId: "faq", scoreBoost: 7 },
  ],
  nodes: {
    start: {
      id: "start",
      message:
        "Bonjour, je peux vous aider à trouver la ressource CPTS adaptée. Choisissez une option ou écrivez votre demande.",
      quickReplies: mainQuickReplies,
    },
    "medecin-traitant": {
      id: "medecin-traitant",
      message: "Pour la recherche de médecin traitant, voici les ressources utiles :",
      quickReplies: [
        {
          id: "qr-voir-annuaire",
          label: "Voir aussi l’annuaire",
          value: "voir annuaire",
          actionResourceIds: ["annuaire"],
        },
        restartQuickReply,
      ],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["medecin-traitant", "ao-questionnaire-medecin", "ao-questionnaire-paramedical"],
        },
      ],
    },
    urgences: {
      id: "urgences",
      message: "En cas de besoin urgent, voici les contacts adaptés :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["coordonnees", "urgence-3114"],
        },
      ],
    },
    "sante-mentale": {
      id: "sante-mentale",
      message: "Pour la santé mentale, je vous propose ces ressources :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["sante-mentale", "sante-mentale-jeunes", "urgence-3114"],
        },
      ],
    },
    annuaire: {
      id: "annuaire",
      message: "Pour trouver un professionnel de santé :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["annuaire"],
        },
      ],
    },
    "presentation-node": {
      id: "presentation-node",
      message: "Pour comprendre la CPTS et ses missions :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["presentation"],
        },
      ],
    },
    "mon-espace-sante-node": {
      id: "mon-espace-sante-node",
      message: "Voici la page dédiée à l'utilisation de Mon Espace Santé :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["mon-espace-sante"],
        },
      ],
    },
    professionnels: {
      id: "professionnels",
      message: "Voici les principales ressources pour les professionnels :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["pro-actions-outils", "pro-supports", "pro-formations"],
        },
      ],
    },
    supports: {
      id: "supports",
      message: "Pour commander des supports, utilisez cette page :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["pro-supports", "contact-email"],
        },
      ],
    },
    formations: {
      id: "formations",
      message: "Pour consulter les formations et vous inscrire :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["pro-formations", "pro-actions-outils"],
        },
      ],
    },
    prevention: {
      id: "prevention",
      message: "Voici les contenus de prévention santé familiale :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["prevention-familiale", "sf-mars-bleu-2026", "memos-suivi"],
        },
      ],
    },
    faq: {
      id: "faq",
      message: "Vous pouvez commencer par la FAQ, puis nous écrire si nécessaire :",
      quickReplies: [restartQuickReply],
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["faq", "contact-email"],
        },
      ],
    },
    fallback: {
      id: "fallback",
      message:
        "Je n’ai pas trouvé de ressource précise. Vous pouvez reformuler votre question ou choisir une catégorie ci-dessous. Pour un besoin médical, contactez votre professionnel de santé. Pour une orientation générale, contactez la CPTS.",
      quickReplies: mainQuickReplies,
      actions: [
        {
          type: "suggest_resources",
          resourceIds: ["contact-email", "coordonnees"],
          message: "Vous pouvez aussi contacter directement :",
        },
      ],
    },
  },
  rules: {
    startNodeId: "start",
    fallbackNodeId: "fallback",
    restartNodeId: "start",
    maxSuggestions: 3,
    minScore: 55,
    fuzzyDistanceThreshold: 1,
    decisionRules: [
      {
        id: "rule-quick-reply-text",
        trigger: "quick_reply_text",
        description: "Si le texte correspond à un choix rapide, suivre sa transition.",
      },
      {
        id: "rule-keyword",
        trigger: "keyword_detected",
        description: "Si un mot-clé est détecté, proposer les 3 meilleures ressources.",
      },
      {
        id: "rule-fallback",
        trigger: "no_match",
        description: "Si aucun match, afficher les catégories et suggérer une reformulation.",
      },
    ],
  },
}
